---
  - name: Téléchargement de nagios
    shell: wget --no-check-certificate -O nagios-core.tar.gz https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-4.4.3/nagios-4.4.3.tar.gz

  - name: Décompil Nagios
    shell: tar xvzf nagios-core.tar.gz

  - name: Installation et compilation de Nagios
    shell: |
      cd nagios-4.4.3/
      ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      make all
      make install-groups-users
      usermod -a -G nagios www-data
      make install
      make install-daemoninit
      make install-commandmode
      make install-config
      make install-webconf
      chown nagios: nagioskey*
      a2enmod rewrite
      a2enmod cgi

  - name: Création de l'utilisateur nagios
    shell: htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin

  - shell: systemctl restart apache2

  - shell: systemctl restart nagios
