---
  - name: Installation des plugins Nagios
    shell: |
      cd
      wget --no-check-certificate -O nagios-plugins.tar.gz https://github.com/nagios-plugins/nagios-plugins/archive/release-2.2.1.tar.gz
      tar xvzf nagios-plugins.tar.gz
      cd nagios-plugins-release-2.2.1
      ./tools/setup
      ./configure
      make
      make install
